[project]
name = "url-extrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests",
    "beautifulsoup4",
    "pandas",
    "scrapy",
    "fastapi",
    "uvicorn",
    "ruff>=0.9.9",
]
